wavefront:
  application:
    name: spring-petclinic
    service: spring-petclinic-api-gateway
management:
  metrics:
    export:
      wavefront:
        api-token: 60c8b1d1-64e6-4076-8b9c-638d9be2755c
        uri: https://wavefront.surf
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
